### PR TITLE
Use slugify instead

### PR DESCRIPTION
**Pull request by Waika28**
The reason you need to change Slugger to Slugify is because it supports Unicode correctly.

```Elixir
iex(1)> Slug.slugify "BoOoOo~~~👻👻"
"booooo"

iex(2)> Slugger.slugify "BoOoOo~~~👻👻"
<<66, 111, 79, 111, 79, 111, 45, 159, 145, 187, 45, 159, 145, 187>>
```

### CODE REVIEW

**Comment by sobolevn** [comment]
Re-triggering CI.

**Comment by sobolevn** [comment]
Ok, here we go

**Comment by sobolevn** [comment]
I would love to merge it and release a new version, if you can help me with the CI.
Can you please remove old Elixir / OTP versions from the matrix build?

**Comment by Waika28** [comment]
@sobolevn, like this?

**Review by sobolevn — COMMENTED** [review]
Exactly, thank you! Let's also bump the minimum version in `hex.pm` to `1.12`

**Comment by sobolevn** [comment]
I will release a new version later today! 👍 

Thanks again!

**Pull request merged**
